version: '3'
services:
  redis:
    image: redis:3.2.4
    ports:
      - "6379"
  sidecar:
    build:
      context: .
      dockerfile: Dockerfile_stable
    ports:
      - "3000:8888"
    command: /usr/bin/supervisord -c /root/config/supervisord/sidecar_supervisord.conf
  asan-vulnerable:
    build:
      context: .
      dockerfile: Dockerfile_stable
    command: /root/fuzzer-files/vulnerable/start
    volumes:
      - ${SYNC_DIR}:/root/sync
    environment:
      - MAXFUZZ_ENABLE_S3=0
      - REDIS_QUEUE_URL=redis:6379
    links:
      - redis
  asan-vulnerable-repro:
    build:
      context: .
      dockerfile: Dockerfile_stable
    command: /root/fuzzer-files/vulnerable/start reproduce
    volumes:
      - ${SYNC_DIR}:/root/sync
    environment:
      - MAXFUZZ_ENABLE_S3=0
      - REDIS_QUEUE_URL=redis:6379
    links:
      - redis
